name: Update Website Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Google Sheets CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1SZHriYyWnoYE6GRHVjEmODpTPu6toc64x_m0vd9KlXU/export?format=csv" -o Recettes.csv

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Configure rclone with Service Account
        run: |
          echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT }}' > service_account.json
          mkdir -p ~/.config/rclone
          echo "[gdrive]
          type = drive
          scope = drive.readonly
          service_account_file = $(pwd)/service_account.json
          " > ~/.config/rclone/rclone.conf

      - name: Ensure img folder exists
        run: mkdir -p img

      - name: Sync Google Drive Folder
        run: |
          rclone sync gdrive:1rX4KQI3DHdx9rtdzrTmjU3dVgrGlUhKW img --progress

      - name: Run Python script
        run: python script.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update website data"
          git push